// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/hoysics/basic-im/app/gateway/internal/biz"
	"github.com/hoysics/basic-im/app/gateway/internal/conf"
	"github.com/hoysics/basic-im/app/gateway/internal/data"
	"github.com/hoysics/basic-im/app/gateway/internal/server"
	"github.com/hoysics/basic-im/app/gateway/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, gateway *conf.Gateway, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(logger, gateway)
	if err != nil {
		return nil, nil, err
	}
	stateRepo := data.NewStateRepo(dataData, logger, gateway)
	connectUseCase := biz.NewConnUseCase(logger, stateRepo, gateway)
	gatewayService := service.NewGatewayService(connectUseCase)
	innerGatewayService := service.NewInnerGatewayService(logger, connectUseCase)
	grpcServer := server.NewGRPCServer(confServer, gatewayService, innerGatewayService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
