// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: api/ipconf/v1/ipconf.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	IpConf_ListIpInfo_FullMethodName = "/api.ipconf.v1.IpConf/ListIpInfo"
)

// IpConfClient is the client API for IpConf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IpConfClient interface {
	ListIpInfo(ctx context.Context, in *ListIpInfoRequest, opts ...grpc.CallOption) (*ListIpInfoReply, error)
}

type ipConfClient struct {
	cc grpc.ClientConnInterface
}

func NewIpConfClient(cc grpc.ClientConnInterface) IpConfClient {
	return &ipConfClient{cc}
}

func (c *ipConfClient) ListIpInfo(ctx context.Context, in *ListIpInfoRequest, opts ...grpc.CallOption) (*ListIpInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIpInfoReply)
	err := c.cc.Invoke(ctx, IpConf_ListIpInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpConfServer is the server API for IpConf service.
// All implementations must embed UnimplementedIpConfServer
// for forward compatibility
type IpConfServer interface {
	ListIpInfo(context.Context, *ListIpInfoRequest) (*ListIpInfoReply, error)
	mustEmbedUnimplementedIpConfServer()
}

// UnimplementedIpConfServer must be embedded to have forward compatible implementations.
type UnimplementedIpConfServer struct {
}

func (UnimplementedIpConfServer) ListIpInfo(context.Context, *ListIpInfoRequest) (*ListIpInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIpInfo not implemented")
}
func (UnimplementedIpConfServer) mustEmbedUnimplementedIpConfServer() {}

// UnsafeIpConfServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IpConfServer will
// result in compilation errors.
type UnsafeIpConfServer interface {
	mustEmbedUnimplementedIpConfServer()
}

func RegisterIpConfServer(s grpc.ServiceRegistrar, srv IpConfServer) {
	s.RegisterService(&IpConf_ServiceDesc, srv)
}

func _IpConf_ListIpInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIpInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpConfServer).ListIpInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpConf_ListIpInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpConfServer).ListIpInfo(ctx, req.(*ListIpInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IpConf_ServiceDesc is the grpc.ServiceDesc for IpConf service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IpConf_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ipconf.v1.IpConf",
	HandlerType: (*IpConfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListIpInfo",
			Handler:    _IpConf_ListIpInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ipconf/v1/ipconf.proto",
}
