// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: api/state/v1/state.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	State_CancelConn_FullMethodName    = "/api.state.v1.State/CancelConn"
	State_CreateMsgChan_FullMethodName = "/api.state.v1.State/CreateMsgChan"
)

// StateClient is the client API for State service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StateClient interface {
	CancelConn(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
	CreateMsgChan(ctx context.Context, opts ...grpc.CallOption) (State_CreateMsgChanClient, error)
}

type stateClient struct {
	cc grpc.ClientConnInterface
}

func NewStateClient(cc grpc.ClientConnInterface) StateClient {
	return &stateClient{cc}
}

func (c *stateClient) CancelConn(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateResponse)
	err := c.cc.Invoke(ctx, State_CancelConn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateClient) CreateMsgChan(ctx context.Context, opts ...grpc.CallOption) (State_CreateMsgChanClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &State_ServiceDesc.Streams[0], State_CreateMsgChan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &stateCreateMsgChanClient{ClientStream: stream}
	return x, nil
}

type State_CreateMsgChanClient interface {
	Send(*ChanMsg) error
	Recv() (*ChanMsg, error)
	grpc.ClientStream
}

type stateCreateMsgChanClient struct {
	grpc.ClientStream
}

func (x *stateCreateMsgChanClient) Send(m *ChanMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *stateCreateMsgChanClient) Recv() (*ChanMsg, error) {
	m := new(ChanMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StateServer is the server API for State service.
// All implementations must embed UnimplementedStateServer
// for forward compatibility
type StateServer interface {
	CancelConn(context.Context, *StateRequest) (*StateResponse, error)
	CreateMsgChan(State_CreateMsgChanServer) error
	mustEmbedUnimplementedStateServer()
}

// UnimplementedStateServer must be embedded to have forward compatible implementations.
type UnimplementedStateServer struct {
}

func (UnimplementedStateServer) CancelConn(context.Context, *StateRequest) (*StateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelConn not implemented")
}
func (UnimplementedStateServer) CreateMsgChan(State_CreateMsgChanServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateMsgChan not implemented")
}
func (UnimplementedStateServer) mustEmbedUnimplementedStateServer() {}

// UnsafeStateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateServer will
// result in compilation errors.
type UnsafeStateServer interface {
	mustEmbedUnimplementedStateServer()
}

func RegisterStateServer(s grpc.ServiceRegistrar, srv StateServer) {
	s.RegisterService(&State_ServiceDesc, srv)
}

func _State_CancelConn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServer).CancelConn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: State_CancelConn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServer).CancelConn(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _State_CreateMsgChan_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StateServer).CreateMsgChan(&stateCreateMsgChanServer{ServerStream: stream})
}

type State_CreateMsgChanServer interface {
	Send(*ChanMsg) error
	Recv() (*ChanMsg, error)
	grpc.ServerStream
}

type stateCreateMsgChanServer struct {
	grpc.ServerStream
}

func (x *stateCreateMsgChanServer) Send(m *ChanMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *stateCreateMsgChanServer) Recv() (*ChanMsg, error) {
	m := new(ChanMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// State_ServiceDesc is the grpc.ServiceDesc for State service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var State_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.state.v1.State",
	HandlerType: (*StateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CancelConn",
			Handler:    _State_CancelConn_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateMsgChan",
			Handler:       _State_CreateMsgChan_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/state/v1/state.proto",
}
