// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/hoysics/basic-im/app/ipconf/internal/biz"
	"github.com/hoysics/basic-im/app/ipconf/internal/conf"
	"github.com/hoysics/basic-im/app/ipconf/internal/data"
	"github.com/hoysics/basic-im/app/ipconf/internal/server"
	"github.com/hoysics/basic-im/app/ipconf/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	sourceRepo := data.NewSourceRepo()
	dispatcher := biz.NewDispatcher(sourceRepo, logger)
	ipConfService := service.NewIpConfService(logger, dispatcher)
	grpcServer := server.NewGRPCServer(confServer, ipConfService, logger)
	httpServer := server.NewHTTPServer(confServer, ipConfService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
