// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/hoysics/basic-im/app/state/internal/biz"
	"github.com/hoysics/basic-im/app/state/internal/conf"
	"github.com/hoysics/basic-im/app/state/internal/data"
	"github.com/hoysics/basic-im/app/state/internal/server"
	"github.com/hoysics/basic-im/app/state/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, state *conf.State, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, state, confServer, logger)
	if err != nil {
		return nil, nil, err
	}
	connStateRepo := data.NewConnStateRepo(logger, dataData)
	cmdHandler := biz.NewCmdHandler(connStateRepo, logger, state)
	gatewayRepo := data.NewGatewayRepo(logger, state)
	gatewayClient := biz.NewGatewayClient(logger, gatewayRepo)
	stateService := service.NewStateService(logger, state, cmdHandler, gatewayClient)
	grpcServer := server.NewGRPCServer(confServer, stateService)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
